services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: jwt-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/app

volumes:
  mongo_data:
